@php($editing = isset($player))
@php($pivot = $editing ? $player->pivot : null)
<div class="box b-a m-b-md"><div class="box-header"><h6 class="m-a-0">{{ __('backend.player_identity') }}</h6></div><div class="box-body"><div class="row">
    @if(!$editing)<div class="col-md-4"><div class="form-group"><label>{{ __('backend.player_id_optional') }}</label><input type="number" name="player_id" value="{{ old('player_id') }}" class="form-control" min="1"><small class="text-muted">{{ __('backend.player_id_hint') }}</small></div></div>@endif
    <div class="col-md-4"><div class="form-group"><label>{{ __('backend.name_ar') }}</label><input name="name_ar" value="{{ old('name_ar', $editing ? $player->name_ar : '') }}" class="form-control" required maxlength="255"></div></div>
    <div class="col-md-4"><div class="form-group"><label>{{ __('backend.name_en') }}</label><input name="name_en" value="{{ old('name_en', $editing ? $player->name_en : '') }}" class="form-control" maxlength="255"></div></div>
    <div class="col-md-4"><div class="form-group"><label>{{ __('backend.common_name') }}</label><input name="common_name" value="{{ old('common_name', $editing ? $player->common_name : '') }}" class="form-control" maxlength="255"></div></div>
    <div class="col-md-4"><div class="form-group"><label>{{ __('backend.date_of_birth') }}</label><input type="date" name="date_of_birth" value="{{ old('date_of_birth', $editing ? $player->date_of_birth : '') }}" class="form-control"></div></div>
    <div class="col-md-4"><div class="form-group"><label>{{ __('backend.gender') }}</label><input name="gender" value="{{ old('gender', $editing ? $player->gender : '') }}" class="form-control" maxlength="20" list="player-genders"><datalist id="player-genders"><option value="male"><option value="female"></datalist></div></div>
    <div class="col-md-4"><div class="form-group"><label>{{ __('backend.country') }}</label><select name="country_id" class="form-control select2" ui-jp="select2" ui-options="{theme:'bootstrap'}"><option value="">{{ __('backend.selectCountry') }}</option>@foreach($countries as $country)<option value="{{ $country->id }}" {{ (string)old('country_id',$editing?$player->country_id:'')===(string)$country->id?'selected':'' }}>{{ $country->$title_var }}</option>@endforeach</select></div></div>
    <div class="col-md-4"><div class="form-group"><label>{{ __('backend.nationality') }}</label><select name="nationality_id" class="form-control select2" ui-jp="select2" ui-options="{theme:'bootstrap'}"><option value="">-</option>@foreach($countries as $country)<option value="{{ $country->id }}" {{ (string)old('nationality_id',$editing?$player->nationality_id:'')===(string)$country->id?'selected':'' }}>{{ $country->$title_var }}</option>@endforeach</select></div></div>
</div></div></div>
<div class="row"><div class="col-md-8"><div class="box b-a m-b-md"><div class="box-header"><h6 class="m-a-0">{{ __('backend.player_sport_data') }}</h6></div><div class="box-body"><div class="row">
    <div class="col-md-4"><div class="form-group"><label>{{ __('backend.height_cm') }}</label><input type="number" step="0.01" name="height" value="{{ old('height',$editing?$player->height:'') }}" class="form-control" min="0" max="300"></div></div>
    <div class="col-md-4"><div class="form-group"><label>{{ __('backend.weight_kg') }}</label><input type="number" step="0.01" name="weight" value="{{ old('weight',$editing?$player->weight:'') }}" class="form-control" min="0" max="500"></div></div>
    <div class="col-md-4"><div class="form-group"><label>{{ __('backend.foot') }}</label><input name="foot" value="{{ old('foot',$editing?$player->foot:'') }}" class="form-control" maxlength="20" list="preferred-feet"><datalist id="preferred-feet"><option value="right"><option value="left"><option value="both"></datalist></div></div>
    <div class="col-md-4"><div class="form-group"><label>{{ __('backend.position_id') }}</label><input type="number" name="position_id" value="{{ old('position_id',$editing?$player->position_id:'') }}" class="form-control" min="1"></div></div>
    <div class="col-md-4"><div class="form-group"><label>{{ __('backend.detailed_position_id') }}</label><input type="number" name="detailed_position_id" value="{{ old('detailed_position_id',$editing?$player->detailed_position_id:'') }}" class="form-control" min="1"></div></div>
    <div class="col-md-4"><div class="form-group"><label>{{ __('backend.sport_id') }}</label><input type="number" name="sport_id" value="{{ old('sport_id',$editing?$player->sport_id:1) }}" class="form-control" min="1"></div></div>
</div></div></div></div>
<div class="col-md-4"><div class="box b-a m-b-md"><div class="box-header"><h6 class="m-a-0">{{ __('backend.player_photo') }}</h6></div><div class="box-body">
    @if($editing && $player->image_path)<div class="text-center m-b"><img id="current_photo" src="{{ $player->image_path }}" style="width:90px;height:90px;object-fit:cover;border-radius:50%">@if($player->local_image)<div class="m-t-sm"><button type="button" class="btn btn-sm btn-default" onclick="document.getElementById('current_photo').style.display='none';document.getElementById('photo_delete').value='1'">{{ __('backend.delete') }}</button><input type="hidden" name="photo_delete" value="0" id="photo_delete"></div>@endif</div>@endif
    <div class="form-group"><input type="file" name="local_image" accept="image/*" class="form-control"></div><div class="form-group"><label>{{ __('backend.image_url') }}</label><input type="url" name="image_path" value="{{ old('image_path',$editing?$player->api_image_path:'') }}" class="form-control" dir="ltr"></div>
</div></div></div></div>
<div class="box b-a"><div class="box-header"><h6 class="m-a-0">{{ __('backend.team_membership') }}</h6><small class="text-muted">{{ __('backend.team_membership_hint') }}</small></div><div class="box-body">@if($editing)<input type="hidden" name="pivot_id" value="{{ $pivot?->id }}">@endif<div class="row">
    <div class="col-md-4"><div class="form-group"><label>{{ __('backend.season') }}</label><select name="season_id" class="form-control select2" ui-jp="select2" ui-options="{theme:'bootstrap'}"><option value="">{{ __('backend.without_season') }}</option>@foreach($seasons as $season)<option value="{{ $season->id }}" {{ (string)old('season_id',$pivot?->season_id)===(string)$season->id?'selected':'' }}>{{ $season->name }}{{ $season->is_current ? ' - '.__('backend.current') : '' }}</option>@endforeach</select></div></div>
    <div class="col-md-2"><div class="form-group"><label>{{ __('backend.jersey_number') }}</label><input type="number" name="jersey_number" value="{{ old('jersey_number',$pivot?->jersey_number) }}" class="form-control" min="0" max="999"></div></div>
    <div class="col-md-3"><div class="form-group"><label>{{ __('backend.team_position_id') }}</label><input type="number" name="team_position_id" value="{{ old('team_position_id',$pivot?->position_id) }}" class="form-control" min="1"></div></div>
    <div class="col-md-3"><div class="form-group"><label>{{ __('backend.team_detailed_position_id') }}</label><input type="number" name="team_detailed_position_id" value="{{ old('team_detailed_position_id',$pivot?->detailed_position_id) }}" class="form-control" min="1"></div></div>
    <div class="col-md-3"><div class="form-group"><label>{{ __('backend.from_date') }}</label><input type="date" name="from_date" value="{{ old('from_date',$pivot?->from_date) }}" class="form-control"></div></div>
    <div class="col-md-3"><div class="form-group"><label>{{ __('backend.to_date') }}</label><input type="date" name="to_date" value="{{ old('to_date',$pivot?->to_date) }}" class="form-control"></div></div>
    <div class="col-md-2"><div class="form-group"><label>{{ __('backend.transfer_id') }}</label><input type="number" name="transfer_id" value="{{ old('transfer_id',$pivot?->transfer_id) }}" class="form-control" min="1"></div></div>
    @foreach(['is_current'=>['status',1],'is_captain'=>['captain',0]] as $field=>$meta)@php($v=(int)old($field,$editing?(int)$pivot?->$field:$meta[1]))<div class="col-md-2"><div class="form-group"><label class="d-block">{{ __('backend.'.$meta[0]) }}</label><label class="md-check"><input type="radio" name="{{ $field }}" value="1" {{ $v===1?'checked':'' }} required><i class="primary"></i> {{ __('backend.yes') }}</label> <label class="md-check"><input type="radio" name="{{ $field }}" value="0" {{ $v===0?'checked':'' }} required><i class="danger"></i> {{ __('backend.no') }}</label></div></div>@endforeach
</div></div></div>
